import React from "react";
import ReactDOM from "react-dom";

import axios from "axios";

import TodoItems from "./TodoItems";
import TodoItem from "./TodoItem";
class ListingApp extends React.Component {
    constructor(props) {
      super(props);
      this.state = {
        listings: []
      };
      this.getListings = this.getListings.bind(this);
  }
  //load ListingApp component after getter 
  componentDidMount() {
    this.getListings();
  }
    //request items at index /api/v1/listings
  getListings() {
    //if successful, load data into state
    axios
      .get("/api/v1/todo_items")
      .then(response => {
        const todoItems = response.data; //bind to the data
        this.setState({ todoItems });
      })
      .catch(error => {
        console.log(error);
      });
    }
    //render items
    render() {
        return (
            //render the listing by mapping over each listing in state, passing unique key id generated by rails
            <Listing>
              {this.state.listings.map(listing=> (
                <Listing key={listing.id} listing={listing} />
              ))}
            </Listing>
          );
    }
  }